### PR TITLE
RF-12842 Allow CSS files with resource EL to be packed

### PR DESCRIPTION
**Pull request by blabno**

### CODE REVIEW

**Comment by lfryc** [comment]
Hey Bernard, thanks for a pull request.

I believe we need to improve this further though.

If you include the EL in the whole CSS package, then you can't effectively cache it on client side - EL evaluation can change the content of a resource, so it should not be cached by a browser and will need to be downloaded.

What we will need to do is expansion of resource ELs.

**Comment by blabno** [comment]
Lukas, I don't understand what you mean by "expansion of resource ELs.". Could you explain?

**Comment by lfryc** [comment]
It means that we will expand the resource links from

```
url(#{resource['images:image.png']});
```

to

```
url('../../images/image.png');
```

Since those resources are served from ResourceServlet, their placement in directory structure will be guaranteed.

**Comment by blabno** [comment]
No, it's not guaranteed. I have icons in resource/img/icons that are used only by qicon.css which is sprite related css file. Those icons are not copied to static resources directory.

**Comment by lfryc** [comment]
We have discussed the problem on IRC - here is transcript: http://transcripts.jboss.org/channel/irc.freenode.org/%23richfaces/2013/%23richfaces.2013-03-26.log.html#t2013-03-26T14:39:17

I believe it's possible but we have agreed that Bernard will show me the issue in action at occasion.

**Comment by bleathem** [comment]
This was inadvertently closed when I dropped the develop branch in favour of developing on the master branch.

**Comment by lfryc** [comment]
Bernard, could you please open your pull request again against master branch?

**Pull request closed without merging**
